.386
STACK SEGMENT USE16 STACK
    DB 200 DUP(0)
STACK ENDS

DATA SEGMENT USE16
    XUEHAO DB 3 DUP(0)
DATA ENDS

CODE SEGMENT USE16
    ASSUME CS:CODE,DS:DATA,SS:STACK
START:
    ; INDIRECT
    MOV BX, OFFSET XUEHAO
    MOV BYTE PTR[BX],'5'
    INC BX
    MOV BYTE PTR[BX],'3'
    INC BX
    MOV BYTE PTR[BX],'0'

    ; RESET XUEHAO
    MOV BX, OFFSET XUEHAO
    MOV BYTE PTR[BX],0
    INC BX
    MOV BYTE PTR[BX],0
    INC BX
    MOV BYTE PTR[BX],0

    ; VARIABLE
    MOV BX, OFFSET XUEHAO
    MOV BYTE PTR[BX],'5'
    MOV BYTE PTR[BX+1],'3'
    MOV BYTE PTR[BX+2],'0'

    ; RESET XUEHAO
    MOV BX, OFFSET XUEHAO
    MOV BYTE PTR[BX],0
    MOV BYTE PTR[BX+1],0
    MOV BYTE PTR[BX+2],0

    ; BASE AND OFFSET
    MOV BX, OFFSET XUEHAO
    MOV SI,0
    MOV BYTE PTR[BX+SI],'5'
    INC SI
    MOV BYTE PTR[BX+SI],'3'
    INC SI
    MOV BYTE PTR[BX+SI],'0'

    ; RESET XUEHAO
    MOV BX, OFFSET XUEHAO
    MOV SI,0
    MOV BYTE PTR[BX+SI],0
    INC SI
    MOV BYTE PTR[BX+SI],0
    INC SI
    MOV BYTE PTR[BX+SI],0

    ; DIRECT
    MOV XUEHAO,'5'
    MOV XUEHAO+1,'3'
    MOV XUEHAO+2,'0'
    
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START
